# Basic Information 
title: Rin Ebe(Zhiyi)
position: M.Phil Candidate
affiliation: Waseda University
subaffiliation: Faculty of Science and Engineering
affiliation_link: https://www.waseda.jp/top/en/
subaffiliation_link: https://www.waseda.jp/fsci/
affiliation_logo: ./assets/img/spinion.svg
email: zzhiyirin (at) gmail.com
# email2: song.chen (at) universite-paris-saclay.fr
address: 3-chōme-4-1 Ōkubo, Shinjuku City, Tokyo 169-8555, Japan
# address_link: https://www.google.fr/maps/place/Spin-Ion+Technologies/@48.7124352,2.194429,17z/data=!3m2!4b1!5s0x47e678bdc29075f7:0xbce23cefe16f4791!4m6!3m5!1s0x47e678bdc3c95555:0xe09ceff0db3725ab!8m2!3d48.7124317!4d2.1970093!16s%2Fg%2F11r4m02q4g?entry=ttu

# Search Engine Optimization (SEO)
keywords: zhiyi zhou, zhou zhiyi, eberin, rin ebe
canonical: https://minimal-light-theme.yliu.me/
description: Song Chen is a Ph.D. canditate at Spin-Ion Technologies and Université Paris-Saclay. His research lies at using magneto-ionics to develop new concepts for magnetic data storage, spintronic devices and magnonics, always with the aim of improving energy efficiency with respect to currently available technologies - with a special focus on the boosting magneto-ionic effect using ion irradiation & ion implantation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
cv_link: 
google_scholar:
github_link:
linkedin: 
researchgate: 

# Images 
avatar: ./assets/img/avatar3.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: ${{ secrets.CLUSTRMAPS_ID }}

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: ${{ secrets.GOOGLE_SCHOLAR_ID }}

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one




# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
